version: "3.8"

services:
  web:
    build: .
    command: bash -c "python3 mongo_seed.py && python3 main.py"
    ports:
      - "5000:5000"
    volumes: 
      - .:/flask-app
    environment: 
      - DB_URI=mongodb://db:27017
    depends_on:
      - db

  db:
    image: mongo:4.4
